Base_finetune_data

In [ ]:
import pandas as pd
import numpy as np
import utils

train_basecase = pd.read_csv("train_preds(train_only)/train_base_preds/train1_predictions.tsv",sep="\t")
originl_data  = pd.read_csv("NLP_dataset/MNLI_formatted/Shared_BaseTrain_MNLI.tsv",sep="\t")

# where data is the eval data and the second originl_train_data is the Shared_BaseTrain_MNLI.tsv data
output = utils.create_fintune_data(data = train_basecase,originl_train_data=originl_data,percent = 0.01)
output.to_csv("iteration1_finetune_train.tsv",sep="\t",index=False)

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]

In [22]:
train_basecase

,textid,target,model,tokenizer,predicted,prob,CONTRADICTION,NEUTRAL,ENTAILMENT
0,0,0,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.684649,0.684649,0.299382,0.015970
1,1,0,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.907651,0.907651,0.087439,0.004910
2,2,0,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.733460,0.171711,0.733460,0.094829
3,3,0,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.581346,0.581346,0.398013,0.020641
4,0,1,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.989744,0.009343,0.989744,0.000913
...,...,...,...,...,...,...,...,...,...
479995,3,119998,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.636300,0.329549,0.636300,0.034151
479996,0,119999,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.741773,0.741773,0.227394,0.030832
479997,1,119999,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.868839,0.092239,0.868839,0.038922
479998,2,119999,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.605917,0.605917,0.335516,0.058567
479999,3,119999,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.806028,0.151934,0.806028,0.042038

In [ ]:
display(output)

output.to_csv("iteration1_finetune_train.tsv",sep="\t",index=False)

,textid,pair,text,label
0,0,This example is Sports,"Madrid, Spain (Sports Network) - Real Madrid #...",ENTAILMENT
1,1,This example is Sports,DALLAS (Sports Network) - Dirk Nowitzki score...,ENTAILMENT
2,2,This example is Sports,"Phoenix, AZ (Sports Network) - Quentin Richard...",ENTAILMENT
3,3,This example is Sports,"ORLANDO, Fl. (Sports Network) - Hedo Turkoglu...",ENTAILMENT
4,4,This example is Sports,"ORLANDO, Fl. (Sports Network) - Hedo Turkoglu...",ENTAILMENT
...,...,...,...,...
2395,2395,This example is Sports,ENGLAND fast bowler Steve Harmison is the worl...,CONTRADICTION
2396,2396,This example is Sci/Tech,"London, England (Sports Network) - Blackburn n...",CONTRADICTION
2397,2397,This example is World,"MOBILE, Ala. (SportsTicker) - After having the...",CONTRADICTION
2398,2398,This example is Business,"Athens, Greece (Sports Network) - Ilias Iliadi...",CONTRADICTION
2399,2399,This example is Business,"Philadelphia, PA (Sports Network) - Philadelph...",CONTRADICTION

In [ ]:
# this is just sanity check for the functions

In [4]:
col = "ENTAILMENT"

# Row with max entailment
max_row = train_basecase.groupby("target")["ENTAILMENT"].max()
second_max_row = train_basecase.groupby("target")["ENTAILMENT"].apply(lambda x: np.partition(x,-2)[-2])

np.max(max_row - second_max_row)
# Row with second max entailment


# print("Max row:\n", max_row)
# print("\nSecond max row:\n", second_max_row)

0.9397252909839154

In [3]:
utils.get_positive_example(train_basecase,percent=0.01)

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]

,textid,target,model,tokenizer,predicted,prob,CONTRADICTION,NEUTRAL,ENTAILMENT,delta
103463,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.951475,0.003559,0.044966,0.951475,0.939725
85323,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.957360,0.001316,0.041324,0.957360,0.937456
115388,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.956853,0.002079,0.041067,0.956853,0.934089
86495,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.949630,0.006331,0.044039,0.949630,0.931534
86513,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.949630,0.006331,0.044039,0.949630,0.931534
...,...,...,...,...,...,...,...,...,...,...
6091,0,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.725080,0.092618,0.182302,0.725080,0.692546
28939,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.834042,0.018724,0.147234,0.834042,0.692496
90024,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.739755,0.019391,0.240854,0.739755,0.691871
1619,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.723906,0.013600,0.262494,0.723906,0.691619
41472,1,entailment,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,ENTAILMENT,0.935842,0.005199,0.058959,0.935842,0.691524

# Chreate the finetune data used to train iteration 2

In [ ]:
train_basecase = pd.read_csv("/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/Model_Outputs/Model_seed_2_Yizhou/iteration_1/model2_iteration_1.tsv",sep="\t")
originl_data  = pd.read_csv("NLP_dataset/MNLI_formatted/Shared_BaseTrain_MNLI.tsv",sep="\t")
train_basecase

,textid,target,model,tokenizer,predicted,prob,CONTRADICTION,ENTAILMENT,NEUTRAL
0,0,0,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.999622,0.999622,0.000330,0.000048
1,1,0,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.998072,0.998072,0.001897,0.000031
2,2,0,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.995554,0.995554,0.003867,0.000579
3,3,0,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.999506,0.999506,0.000425,0.000069
4,0,1,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.999615,0.999615,0.000343,0.000041
...,...,...,...,...,...,...,...,...,...
479995,3,119998,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.999723,0.999723,0.000216,0.000061
479996,0,119999,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.999677,0.999677,0.000234,0.000088
479997,1,119999,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.751913,0.751913,0.248050,0.000037
479998,2,119999,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.999097,0.999097,0.000838,0.000066
479999,3,119999,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,../NLP_426/MNLI_Model2/finetune2/iteration_1/m...,CONTRADICTION,0.999690,0.999690,0.000248,0.000062

In [5]:
utils.get_positive_example(train_basecase,percent=0.01)["textid"].unique()

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]

array([1])

In [6]:


output = utils.create_fintune_data(data = train_basecase,originl_train_data=originl_data,percent = 0.01)

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]

In [8]:
output.to_csv("iteration2_finetune_train.tsv",sep="\t",index=False)

# We got the evaluation that otput from iteration 2 now we take it and get a finetune for the final models

In [ ]:
import pandas as pd
import numpy as np
import utils


train_basecase = pd.read_csv("Model_Outputs/Model_seed_2_Yizhou/iteration_2/model2_iteration_2.tsv",sep="\t")
originl_data  = pd.read_csv("NLP_dataset/MNLI_formatted/Shared_BaseTrain_MNLI.tsv",sep="\t")

# where data is the eval data and the second originl_train_data is the Shared_BaseTrain_MNLI.tsv data
output = utils.create_fintune_data(data = train_basecase,originl_train_data=originl_data,percent = 0.01)
output.to_csv("Model_Outputs/Model_seed_2_Yizhou/final_finetune/final_finetune_train.tsv",sep="\t",index=False)

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)
/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_percent_df["target"] =  int(len(df_sorted_delta)*percent) * [score_cols[0]]