## Base_Case_Evaluation

In [122]:
import utils
import pandas as pd
import numpy as np


text_classfication_true = pd.read_csv("NLP_dataset/Base_test_textClassification_AgNews.tsv",sep="\t")
MNLI_Basecase =  pd.read_csv("base_preds(tests_only)/initial_base_preds/test2_predictions.tsv",sep="\t")


Max_entailment = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")

mapping_mask =  {0:"World" ,1:"Sports",2:"Business",3:"Sci/Tech"}

text_classfication_true["predicted"] =  Max_entailment["textid"].map(mapping_mask)

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

In [123]:
text_classfication_true["class"].value_counts()

class
Business    1900
Sci/Tech    1900
Sports      1900
World       1900
Name: count, dtype: int64

In [124]:
Max_entailment_Top = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")


# Sanity Check should not equal
np.min(Max_entailment["ENTAILMENT"])
np.min(MNLI_Basecase["ENTAILMENT"])


# Sanity Check should equal
np.max(Max_entailment["ENTAILMENT"])
np.max(MNLI_Basecase["ENTAILMENT"])

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

0.968251883983612

In [126]:
# Calculate Base case accuracy
# CONTRADICTION	NEUTRAL	ENTAILMENT
print(sum(Max_entailment["predicted"]=="ENTAILMENT"))
accruacy = sum(text_classfication_true["class"]==text_classfication_true["predicted"])/len(text_classfication_true["class"])
accruacy

177

0.3285526315789474

In [127]:
Max_entailment["textid"].value_counts()

textid
2    2417
1    2218
3    1874
0    1091
Name: count, dtype: int64

In [144]:
import utils
import pandas as pd
import numpy as np


text_classfication_true = pd.read_csv("NLP_dataset/Base_test_textClassification_AgNews.tsv",sep="\t")
MNLI_Basecase =  pd.read_csv("Model_Outputs/Model_seed_2_Yizhou/final_finetune/model2_final_eval.tsv",sep="\t")



Max_entailment = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")

mapping_mask =  {0:"World" ,1:"Sports",2:"Business",3:"Sci/Tech"}

text_classfication_true["predicted"] =  Max_entailment["textid"].map(mapping_mask)
print(sum(Max_entailment["predicted"]=="ENTAILMENT"))

accruacy = sum(text_classfication_true["class"]==text_classfication_true["predicted"])/len(text_classfication_true["class"])
accruacy

3325

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

0.2501315789473684

In [145]:
Max_entailment

,textid,target,model,tokenizer,predicted,prob,CONTRADICTION,ENTAILMENT,NEUTRAL
0,1,0,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,CONTRADICTION,0.966686,0.966686,0.033313,1.184230e-06
1,1,1,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,ENTAILMENT,0.999997,0.000002,0.999997,4.321143e-08
2,1,2,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,ENTAILMENT,0.999821,0.000179,0.999821,2.986281e-07
3,1,3,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,ENTAILMENT,0.999995,0.000005,0.999995,6.327829e-08
4,1,4,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,ENTAILMENT,0.999991,0.000009,0.999991,1.054667e-07
...,...,...,...,...,...,...,...,...,...
7595,1,7595,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,CONTRADICTION,0.999991,0.999991,0.000009,6.330654e-08
7596,1,7596,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,ENTAILMENT,0.999997,0.000003,0.999997,4.443047e-08
7597,1,7597,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,ENTAILMENT,0.999997,0.000003,0.999997,4.442234e-08
7598,1,7598,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,ENTAILMENT,0.944499,0.055494,0.944499,6.086464e-06
7599,1,7599,../NLP_426/MNLI_Model2/finetune2/final_output/...,../NLP_426/MNLI_Model2/finetune2/final_output/...,CONTRADICTION,0.999997,0.999997,0.000003,2.427837e-08

In [146]:
text_classfication_true

                                                   text     class predicted
0     Unions representing workers at Turner   Newall...  Business    Sports
1     SPACE.com - TORONTO, Canada -- A second\team o...  Sci/Tech    Sports
2     AP - A company founded by a chemistry research...  Sci/Tech    Sports
3     AP - It's barely dawn when Mike Fitzpatrick st...  Sci/Tech    Sports
4     AP - Southern California's smog-fighting agenc...  Sci/Tech    Sports
...                                                 ...       ...       ...
7595  Ukrainian presidential candidate Viktor Yushch...     World    Sports
7596  With the supply of attractive pitching options...    Sports    Sports
7597  Like Roger Clemens did almost exactly eight ye...    Sports    Sports
7598  SINGAPORE : Doctors in the United States have ...  Business    Sports
7599  EBay plans to buy the apartment and home renta...  Business    Sports

[7600 rows x 3 columns]

In [147]:
Max_entailment["textid"].map(mapping_mask).value_counts()

textid
Sports      7598
World          1
Sci/Tech       1
Name: count, dtype: int64

# Model 2 evaluation

In [148]:

text_classfication_true = pd.read_csv("NLP_dataset/Base_test_textClassification_AgNews.tsv",sep="\t")
MNLI_Basecase =  pd.read_csv("Model_Outputs/Model_seed_2_Yizhou//final_finetune/model2_final_eval.tsv",sep="\t")
Max_entailment = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")

mapping_mask =  {0:"World" ,1:"Sports",2:"Business",3:"Sci/Tech"}

text_classfication_true["predicted"] =  Max_entailment["textid"].map(mapping_mask)
print(sum(Max_entailment["predicted"]=="ENTAILMENT"))

accruacy = sum(text_classfication_true["class"]==text_classfication_true["predicted"])/len(text_classfication_true["class"])
accruacy

3325

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

0.2501315789473684

In [149]:
Max_entailment["textid"].value_counts()

textid
1    7598
0       1
3       1
Name: count, dtype: int64

# Train ACCURACY EVALUATION

In [150]:
# Check within train accuracy



text_classfication_true = pd.read_csv("NLP_dataset/MNLI_formatted/Shared_BaseTrain_MNLI.tsv",sep="\t")
MNLI_Basecase =  pd.read_csv("Model_Outputs/Model_seed_2_Yizhou//iteration_2/model2_iteration_2.tsv",sep="\t")



Max_entailment = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")

mapping_mask =  {0:"World" ,1:"Sports",2:"Business",3:"Sci/Tech"}

text_classfication_true["predicted"] =  Max_entailment["textid"].map(mapping_mask)
print(sum(Max_entailment["predicted"]=="ENTAILMENT"))

accruacy = sum(text_classfication_true["class"]==text_classfication_true["predicted"])/len(text_classfication_true["class"])
accruacy

22255

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

0.0624

In [151]:
text_classfication_true = pd.read_csv("NLP_dataset/MNLI_formatted/Shared_BaseTrain_MNLI.tsv",sep="\t")
MNLI_Basecase =  pd.read_csv("Model_Outputs/Model_seed_2_Yizhou//iteration_2/model2_iteration_2.tsv",sep="\t")



Max_entailment = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")

mapping_mask =  {0:"World" ,1:"Sports",2:"Business",3:"Sci/Tech"}

text_classfication_true["predicted"] =  Max_entailment["textid"].map(mapping_mask)
print(sum(Max_entailment["predicted"]=="ENTAILMENT"))

accruacy = sum(text_classfication_true["class"]==text_classfication_true["predicted"])/len(text_classfication_true["class"])
accruacy

22255

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

0.0624

In [152]:

text_classfication_true = pd.read_csv("NLP_dataset/MNLI_formatted/Shared_BaseTrain_MNLI.tsv",sep="\t")
MNLI_Basecase =  pd.read_csv("train_preds(train_only)/train_base_preds/train1_predictions.tsv",sep="\t")



Max_entailment = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")

mapping_mask =  {0:"World" ,1:"Sports",2:"Business",3:"Sci/Tech"}

text_classfication_true["predicted"] =  Max_entailment["textid"].map(mapping_mask)
print(sum(Max_entailment["predicted"]=="ENTAILMENT"))

accruacy = sum(text_classfication_true["class"]==text_classfication_true["predicted"])/len(text_classfication_true["class"])
accruacy

3136

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

0.0628625

In [153]:
Max_entailment

,textid,target,model,tokenizer,predicted,prob,CONTRADICTION,NEUTRAL,ENTAILMENT
0,2,0,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.733460,0.171711,0.733460,0.094829
1,3,1,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.981615,0.016622,0.981615,0.001762
2,2,2,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.585761,0.585761,0.391396,0.022843
3,1,3,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.726445,0.210192,0.726445,0.063362
4,0,4,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.830595,0.086212,0.830595,0.083193
...,...,...,...,...,...,...,...,...,...
119995,2,119995,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.714396,0.237296,0.714396,0.048308
119996,2,119996,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.808074,0.808074,0.165522,0.026403
119997,1,119997,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.736584,0.208652,0.736584,0.054764
119998,1,119998,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,NEUTRAL,0.748055,0.108366,0.748055,0.143580
119999,2,119999,microsoft/deberta-base-mnli,microsoft/deberta-base-mnli,CONTRADICTION,0.605917,0.605917,0.335516,0.058567

In [ ]:
text_classfication_true

,textid,class,text,pair,target,predicted
0,0,World,"Reuters - Short-sellers, Wall Street's dwindli...",This example is World,0,Business
1,1,Sports,"Reuters - Short-sellers, Wall Street's dwindli...",This example is Sports,0,Sci/Tech
2,2,Business,"Reuters - Short-sellers, Wall Street's dwindli...",This example is Bussiness,0,Business
3,3,Sci/Tech,"Reuters - Short-sellers, Wall Street's dwindli...",This example is Sci/Tech,0,Sports
4,0,World,Reuters - Private investment firm Carlyle Grou...,This example is World,1,World
...,...,...,...,...,...,...
479995,3,Sci/Tech,PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...,This example is Sci/Tech,119998,NaN
479996,0,World,INDIANAPOLIS -- All-Star Vince Carter was trad...,This example is World,119999,NaN
479997,1,Sports,INDIANAPOLIS -- All-Star Vince Carter was trad...,This example is Sports,119999,NaN
479998,2,Business,INDIANAPOLIS -- All-Star Vince Carter was trad...,This example is Bussiness,119999,NaN
479999,3,Sci/Tech,INDIANAPOLIS -- All-Star Vince Carter was trad...,This example is Sci/Tech,119999,NaN

# Evlauatioon on model 3

In [155]:

text_classfication_true = pd.read_csv("NLP_dataset/Base_test_textClassification_AgNews.tsv",sep="\t")
MNLI_Basecase =  pd.read_csv("Model_Outputs/Model_seed_3_Osvaldo/eval3_predictions.tsv",sep="\t")
Max_entailment = utils.top_entailment_per_target(MNLI_Basecase,"ENTAILMENT")

mapping_mask =  {0:"World" ,1:"Sports",2:"Business",3:"Sci/Tech"}

text_classfication_true["predicted"] =  Max_entailment["textid"].map(mapping_mask)
print(sum(Max_entailment["predicted"]=="ENTAILMENT"))

accruacy = sum(text_classfication_true["class"]==text_classfication_true["predicted"])/len(text_classfication_true["class"])
accruacy

6674

/Users/apple/Documents/GitHub/NLP_Midterm_Osvaldo_Yizhou_David/utils.py:16: FutureWarning: The 'axis' keyword in SeriesGroupBy.idxmax is deprecated and will be removed in a future version. Call without passing 'axis' instead.
  idx = df.groupby('target')[entail].idxmax(axis=0)

0.2513157894736842

In [142]:
Max_entailment["textid"].map(mapping_mask).value_counts()

textid
Sports      7502
Business      61
World         37
Name: count, dtype: int64